[workspace]
members = [
  "cli", 
  "examples/concepts/accounts-to-storage/*"
]
resolver = "2"

[workspace.dependencies]
alloy-primitives = "=0.8.20"
anchor-lang = "0.31.1"
borsh = "1.5.7"
borsh-derive = "1.5.7"
mollusk-svm = "0.4.1"
solana-account = "2.2.1"
solana-program = "2.3.0"
solana-pubkey = "2.4.0"
solana-sdk-ids = "2.2.1"
solana-system-interface = "1.0.0"
stylus-sdk = "0.9.0"
tokio = "1.46.1"
