[package]
name = "stylusport-mcp-server"
version = "0.1.0"
edition = "2024"

# dependencies are vendored to reduce risk of supply chain attack
# see mcp/vendor for sources and mcp/config.toml for local redirects 
[dependencies]
rust-mcp-schema = "0.7.4"
serde_json = "1.0.143"
